name: Deploy to AWS Amplify (Manual)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: AKIAVKPDLT3TXKKK227D
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install and Build Application
        run: |
          npm ci
          npm run build

      - name: Zip and Upload to S3
        run: |
          cd dist
          zip -r ../deploy.zip .
          cd ..
          aws s3 cp deploy.zip s3://mys3bucket02071992/deploy.zip
          URL=$(aws s3 presign s3://mys3bucket02071992/deploy.zip --expires-in 600)
          echo "DEPLOY_URL=$URL" >> $GITHUB_ENV

      - name: Publish Artifact to Amplify
        run: |
          aws amplify start-deployment \
            --app-id daej0ec32nb5y \
            --branch-name main \
            --source-url "${{ env.DEPLOY_URL }}"
